// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_task_systems/test/unit/product_list_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_task_systems/data/datasources/local/favorite_local_datasource.dart'
    as _i3;
import 'package:flutter_task_systems/data/datasources/local/product_local_datasource.dart'
    as _i7;
import 'package:flutter_task_systems/data/datasources/remote/product_remote_datasource.dart'
    as _i2;
import 'package:flutter_task_systems/data/models/product_model.dart' as _i4;
import 'package:flutter_task_systems/data/repositories/product_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductRemoteDatasource_0 extends _i1.SmartFake
    implements _i2.ProductRemoteDatasource {
  _FakeProductRemoteDatasource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFavoriteLocalDatasource_1 extends _i1.SmartFake
    implements _i3.FavoriteLocalDatasource {
  _FakeFavoriteLocalDatasource_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProduct_2 extends _i1.SmartFake implements _i4.Product {
  _FakeProduct_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i5.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductRemoteDatasource get productApi => (super.noSuchMethod(
        Invocation.getter(#productApi),
        returnValue: _FakeProductRemoteDatasource_0(
          this,
          Invocation.getter(#productApi),
        ),
      ) as _i2.ProductRemoteDatasource);

  @override
  _i3.FavoriteLocalDatasource get favoriteDatasource => (super.noSuchMethod(
        Invocation.getter(#favoriteDatasource),
        returnValue: _FakeFavoriteLocalDatasource_1(
          this,
          Invocation.getter(#favoriteDatasource),
        ),
      ) as _i3.FavoriteLocalDatasource);

  @override
  _i6.Future<List<_i4.Product>> getProducts({int? limit = 20}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
          {#limit: limit},
        ),
        returnValue: _i6.Future<List<_i4.Product>>.value(<_i4.Product>[]),
      ) as _i6.Future<List<_i4.Product>>);

  @override
  _i6.Future<_i4.Product> getProductById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [id],
        ),
        returnValue: _i6.Future<_i4.Product>.value(_FakeProduct_2(
          this,
          Invocation.method(
            #getProductById,
            [id],
          ),
        )),
      ) as _i6.Future<_i4.Product>);

  @override
  _i6.Future<void> addToFavorites(_i4.Product? product) => (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [product],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeFromFavorites(int? productId) => (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [productId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isFavorite(int? productId) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [productId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<_i4.Product>> getFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue: _i6.Future<List<_i4.Product>>.value(<_i4.Product>[]),
      ) as _i6.Future<List<_i4.Product>>);
}

/// A class which mocks [ProductLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductLocalDatasource extends _i1.Mock
    implements _i7.ProductLocalDatasource {
  MockProductLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> cacheProducts(List<_i4.Product>? products) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheProducts,
          [products],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i4.Product>> getAllCachedProducts() => (super.noSuchMethod(
        Invocation.method(
          #getAllCachedProducts,
          [],
        ),
        returnValue: _i6.Future<List<_i4.Product>>.value(<_i4.Product>[]),
      ) as _i6.Future<List<_i4.Product>>);

  @override
  _i6.Future<_i4.Product?> getProductById(int? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [productId],
        ),
        returnValue: _i6.Future<_i4.Product?>.value(),
      ) as _i6.Future<_i4.Product?>);

  @override
  _i6.Future<bool> isProductCached(int? productId) => (super.noSuchMethod(
        Invocation.method(
          #isProductCached,
          [productId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<int> getCacheCount() => (super.noSuchMethod(
        Invocation.method(
          #getCacheCount,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i4.Product>> searchCachedProducts(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCachedProducts,
          [query],
        ),
        returnValue: _i6.Future<List<_i4.Product>>.value(<_i4.Product>[]),
      ) as _i6.Future<List<_i4.Product>>);

  @override
  _i6.Future<List<_i4.Product>> getByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByCategory,
          [category],
        ),
        returnValue: _i6.Future<List<_i4.Product>>.value(<_i4.Product>[]),
      ) as _i6.Future<List<_i4.Product>>);

  @override
  _i6.Future<void> updateCache(List<_i4.Product>? newProducts) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCache,
          [newProducts],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> getCacheStats() => (super.noSuchMethod(
        Invocation.method(
          #getCacheStats,
          [],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<bool> hasCachedData() => (super.noSuchMethod(
        Invocation.method(
          #hasCachedData,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}
